# Generated by Django 5.1.3 on 2026-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
